### ISSUE TITLE
Documentation doesn't match reality

### ISSUE THREAD

**Issue by dmorgantini** [tes/conflab#8]
var Conflab = require('conflab');
Conflab.load(function(err, config) {
    app.listen(config.server.port, config.service.host);
});

^^^ Doesn't work.

/Users/dmorgantini/dev/profiles/service-seguir-api/setup/config.js:21
    conflab.load(function(err, config) {
            ^
TypeError: Object function Config() {
} has no method 'load'
    at module.exports (/Users/dmorgantini/dev/profiles/service-seguir-api/setup/config.js:21:13)
    at Object.<anonymous> (/Users/dmorgantini/dev/profiles/service-seguir-api/node_modules/seguir/bin/seguir.js:42:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by tomruttle** [comment]
Need to instantiate Conflab first. Have updated README.
